{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 1,
    "last_updated": "2025-05-10T20:50:33.293324",
    "severity_distribution": {
      "critical": 0,
      "high": 0,
      "medium": 1,
      "low": 0,
      "none": 0
    }
  },
  "cves": [
    {
      "id": "CVE-2025-4515",
      "publishedDate": "2025-05-10T20:31:04.532Z",
      "lastModifiedDate": "2025-05-10T20:31:04.532Z",
      "description": "A vulnerability, which was classified as problematic, was found in Zylon PrivateGPT up to 0.6.2. This affects an unknown part of the file settings.yaml. The manipulation of the argument allow_origins leads to permissive cross-domain policy with untrusted domains. It is possible to initiate the attack remotely. The exploit has been disclosed to the public and may be used. The vendor was contacted early about this disclosure but did not respond in any way.",
      "severity": 4.3,
      "references": [
        {
          "url": "https://vuldb.com/?id.308235",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?ctiid.308235",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?submit.564451",
          "type": "reference"
        },
        {
          "url": "https://gist.github.com/superboy-zjc/2a727cb0c1d468f21a91e0416d006ffe",
          "type": "poc"
        }
      ],
      "affected": [
        {
          "vendor": "Zylon",
          "product": "PrivateGPT",
          "versions": [
            {
              "version": "0.6.0",
              "status": "affected"
            },
            {
              "version": "0.6.1",
              "status": "affected"
            },
            {
              "version": "0.6.2",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "Permissive Cross-domain Policy with Untrusted Domains",
        "Origin Validation Error"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}