{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 2,
    "last_updated": "2025-04-16T21:24:58.486269",
    "severity_distribution": {
      "critical": 0,
      "high": 1,
      "medium": 0,
      "low": 1,
      "none": 0
    }
  },
  "cves": [
    {
      "id": "CVE-2025-3729",
      "publishedDate": "2025-04-16T21:00:13.318Z",
      "lastModifiedDate": "2025-04-16T21:00:13.318Z",
      "description": "A vulnerability, which was classified as critical, has been found in SourceCodester Web-based Pharmacy Product Management System 1.0. This issue affects some unknown processing of the file backup.php of the component Database Backup Handler. The manipulation of the argument txtdbname leads to os command injection. The attack may be initiated remotely. The exploit has been disclosed to the public and may be used.",
      "severity": 7.3,
      "references": [
        {
          "url": "https://vuldb.com/?id.305075",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?ctiid.305075",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?submit.553631",
          "type": "reference"
        },
        {
          "url": "https://github.com/yaklang/IRifyScanResult/blob/main/Web-based%20Pharmacy%20Product%20Management%20System/rce_in_backup.md",
          "type": "poc"
        },
        {
          "url": "https://www.sourcecodester.com/",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "SourceCodester",
          "product": "Web-based Pharmacy Product Management System",
          "versions": [
            {
              "version": "1.0",
              "status": "affected"
            }
          ],
          "modules": [
            "Database Backup Handler"
          ]
        }
      ],
      "problemType": [
        "OS Command Injection",
        "Command Injection"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-3730",
      "publishedDate": "2025-04-16T21:00:17.836Z",
      "lastModifiedDate": "2025-04-16T21:00:17.836Z",
      "description": "A vulnerability, which was classified as problematic, was found in PyTorch 2.6.0. Affected is the function torch.nn.functional.ctc_loss of the file aten/src/ATen/native/LossCTC.cpp. The manipulation leads to denial of service. An attack has to be approached locally. The exploit has been disclosed to the public and may be used. The name of the patch is 46fc5d8e360127361211cb237d5f9eef0223e567. It is recommended to apply a patch to fix this issue.",
      "severity": 3.3,
      "references": [
        {
          "url": "https://vuldb.com/?id.305076",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?ctiid.305076",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?submit.553645",
          "type": "reference"
        },
        {
          "url": "https://github.com/pytorch/pytorch/issues/150835",
          "type": "reference"
        },
        {
          "url": "https://github.com/pytorch/pytorch/pull/150981",
          "type": "reference"
        },
        {
          "url": "https://github.com/pytorch/pytorch/issues/150835#issue-2979082232",
          "type": "poc"
        },
        {
          "url": "https://github.com/timocafe/tewart-pytorch/commit/46fc5d8e360127361211cb237d5f9eef0223e567",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "n/a",
          "product": "PyTorch",
          "versions": [
            {
              "version": "2.6.0",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "Denial of Service"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}