{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 1,
    "last_updated": "2025-06-03T21:32:24.750223",
    "severity_distribution": {
      "critical": 0,
      "high": 0,
      "medium": 1,
      "low": 0,
      "none": 0
    }
  },
  "cves": [
    {
      "id": "CVE-2024-12718",
      "publishedDate": "2025-06-03T12:59:10.908Z",
      "lastModifiedDate": "2025-06-03T21:19:55.570Z",
      "description": "Allows modifying some file metadata (e.g. last modified) with filter=\"data\" or file permissions (chmod) with filter=\"tar\" of files outside the extraction directory.\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
      "severity": 5.3,
      "references": [
        {
          "url": "https://github.com/python/cpython/issues/135034",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/pull/135037",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/issues/127987",
          "type": "reference"
        },
        {
          "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
          "type": "reference"
        },
        {
          "url": "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "defaultStatus": "unaffected",
          "product": "CPython",
          "repo": "https://github.com/python/cpython",
          "vendor": "Python Software Foundation",
          "versions": [
            {
              "version": "0",
              "lessThan": "3.9.23",
              "status": "affected",
              "versionType": "python"
            },
            {
              "version": "3.10.0",
              "lessThan": "3.10.18",
              "status": "affected",
              "versionType": "python"
            },
            {
              "version": "3.11.0",
              "lessThan": "3.11.13",
              "status": "affected",
              "versionType": "python"
            },
            {
              "version": "3.12.0",
              "lessThan": "3.12.11",
              "status": "affected",
              "versionType": "python"
            },
            {
              "version": "3.13.0",
              "lessThan": "3.13.4",
              "status": "affected",
              "versionType": "python"
            },
            {
              "version": "3.14.0a1",
              "lessThan": "3.14.0",
              "status": "affected",
              "versionType": "python"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-22 Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}