{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 1,
    "last_updated": "2025-06-07T07:57:46.736794",
    "severity_distribution": {
      "critical": 0,
      "high": 0,
      "medium": 0,
      "low": 0,
      "none": 1
    }
  },
  "cves": [
    {
      "id": "CVE-2025-5399",
      "publishedDate": "2025-06-07T07:49:09.370Z",
      "lastModifiedDate": "2025-06-07T07:49:09.370Z",
      "description": "Due to a mistake in libcurl's WebSocket code, a malicious server can send a\nparticularly crafted packet which makes libcurl get trapped in an endless\nbusy-loop.\n\nThere is no other way for the application to escape or exit this loop other\nthan killing the thread/process.\n\nThis might be used to DoS libcurl-using application.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://curl.se/docs/CVE-2025-5399.json",
          "type": "reference"
        },
        {
          "url": "https://curl.se/docs/CVE-2025-5399.html",
          "type": "reference"
        },
        {
          "url": "https://hackerone.com/reports/3168039",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "curl",
          "product": "curl",
          "versions": [
            {
              "version": "8.14.0",
              "status": "affected",
              "lessThanOrEqual": "8.14.0",
              "versionType": "semver"
            },
            {
              "version": "8.13.0",
              "status": "affected",
              "lessThanOrEqual": "8.13.0",
              "versionType": "semver"
            }
          ],
          "defaultStatus": "unaffected"
        }
      ],
      "problemType": [
        "CWE-835 Loop with Unreachable Exit Condition ('Infinite Loop')"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}