{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 3,
    "last_updated": "2025-05-16T18:16:14.500553",
    "severity_distribution": {
      "critical": 0,
      "high": 2,
      "medium": 0,
      "low": 0,
      "none": 1
    }
  },
  "cves": [
    {
      "id": "CVE-2025-4794",
      "publishedDate": "2025-05-16T18:00:13.866Z",
      "lastModifiedDate": "2025-05-16T18:00:13.866Z",
      "description": "A vulnerability was found in PHPGurukul Online Course Registration 3.1. It has been declared as critical. Affected by this vulnerability is an unknown functionality of the file /news.php. The manipulation of the argument newstitle leads to sql injection. The attack can be launched remotely. The exploit has been disclosed to the public and may be used.",
      "severity": 7.3,
      "references": [
        {
          "url": "https://vuldb.com/?id.309103",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?ctiid.309103",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?submit.572508",
          "type": "reference"
        },
        {
          "url": "https://github.com/FLYFISH567/CVE/issues/8",
          "type": "poc"
        },
        {
          "url": "https://phpgurukul.com/",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "PHPGurukul",
          "product": "Online Course Registration",
          "versions": [
            {
              "version": "3.1",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "SQL Injection",
        "Injection"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-4793",
      "publishedDate": "2025-05-16T18:00:10.610Z",
      "lastModifiedDate": "2025-05-16T18:00:10.610Z",
      "description": "A vulnerability was found in PHPGurukul Online Course Registration 3.1. It has been classified as critical. Affected is an unknown function of the file /edit-student-profile.php. The manipulation of the argument cgpa leads to sql injection. It is possible to launch the attack remotely. The exploit has been disclosed to the public and may be used.",
      "severity": 7.3,
      "references": [
        {
          "url": "https://vuldb.com/?id.309102",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?ctiid.309102",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?submit.572507",
          "type": "reference"
        },
        {
          "url": "https://github.com/FLYFISH567/CVE/issues/7",
          "type": "poc"
        },
        {
          "url": "https://phpgurukul.com/",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "PHPGurukul",
          "product": "Online Course Registration",
          "versions": [
            {
              "version": "3.1",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "SQL Injection",
        "Injection"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-4516",
      "publishedDate": "2025-05-15T13:29:20.126Z",
      "lastModifiedDate": "2025-05-16T18:03:58.514Z",
      "description": "There is an issue in CPython when using `bytes.decode(\"unicode_escape\", error=\"ignore|replace\")`. If you are not using the \"unicode_escape\" encoding or an error handler your usage is not affected. To work-around this issue you may stop using the error= handler and instead wrap the bytes.decode() call in a try-except catching the DecodeError.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://github.com/python/cpython/issues/133767",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/pull/129648",
          "type": "reference"
        },
        {
          "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/L75IPBBTSCYEF56I2M4KIW353BB3AY74/",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/commit/69b4387f78f413e8c47572a85b3478c47eba8142",
          "type": "reference"
        },
        {
          "url": "https://github.com/python/cpython/commit/9f69a58623bd01349a18ba0c7a9cb1dad6a51e8e",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "defaultStatus": "unaffected",
          "product": "CPython",
          "repo": "https://github.com/python/cpython",
          "vendor": "Python Software Foundation",
          "versions": [
            {
              "lessThan": "3.14.0b1",
              "status": "affected",
              "version": "0",
              "versionType": "python"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-416 Use After Free"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}