{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 1,
    "last_updated": "2025-06-02T08:56:58.624038",
    "severity_distribution": {
      "critical": 0,
      "high": 0,
      "medium": 0,
      "low": 0,
      "none": 1
    }
  },
  "cves": [
    {
      "id": "CVE-2025-5455",
      "publishedDate": "2025-06-02T08:46:20.524Z",
      "lastModifiedDate": "2025-06-02T08:46:20.524Z",
      "description": "An issue was found in the private API function qDecodeDataUrl() in QtCore, which is used in QTextDocument and QNetworkReply, and, potentially, in user code.\n\nIf the function was called with malformed data, for example, an URL that\ncontained a \"charset\" parameter that lacked a value (such as\n\"data:charset,\"), and Qt was built with assertions enabled, then it would hit an assertion, resulting in a denial of service\n(abort).\n\nThis impacts Qt up to 5.15.18, 6.0.0->6.5.8, 6.6.0->6.8.3 and 6.9.0. This has been fixed in 5.15.19, 6.5.9, 6.8.4 and 6.9.1.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://codereview.qt-project.org/c/qt/qtbase/+/642006",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "defaultStatus": "unaffected",
          "product": "Qt",
          "vendor": "The Qt Company",
          "versions": [
            {
              "lessThanOrEqual": "5.15.18",
              "status": "affected",
              "version": "0",
              "versionType": "python"
            },
            {
              "lessThanOrEqual": "6.5.8",
              "status": "affected",
              "version": "6.0.0",
              "versionType": "python"
            },
            {
              "status": "unaffected",
              "version": "6.5.9",
              "versionType": "python"
            },
            {
              "lessThanOrEqual": "6.8.3",
              "status": "affected",
              "version": "6.6.0",
              "versionType": "python"
            },
            {
              "status": "unaffected",
              "version": "6.8.4",
              "versionType": "python"
            },
            {
              "status": "affected",
              "version": "6.9.0",
              "versionType": "python"
            },
            {
              "status": "unaffected",
              "version": "6.9.1",
              "versionType": "python"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-20 Improper Input Validation"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}