{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 1,
    "last_updated": "2025-04-20T03:57:45.673130",
    "severity_distribution": {
      "critical": 0,
      "high": 0,
      "medium": 1,
      "low": 0,
      "none": 0
    }
  },
  "cves": [
    {
      "id": "CVE-2025-43929",
      "publishedDate": "2025-04-20T00:00:00.000Z",
      "lastModifiedDate": "2025-04-20T02:23:05.648Z",
      "description": "open_actions.py in kitty before 0.41.0 does not ask for user confirmation before running a local executable file that may have been linked from an untrusted document (e.g., a document opened in KDE ghostwriter).",
      "severity": 4.1,
      "references": [
        {
          "url": "https://github.com/kovidgoyal/kitty/commit/ce5cfdd9caf44c538af800a07162e1f49bd53c35",
          "type": "reference"
        },
        {
          "url": "https://github.com/kovidgoyal/kitty/compare/v0.40.1...v0.41.0",
          "type": "reference"
        },
        {
          "url": "https://ghostwriter.kde.org/documentation/#links",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "defaultStatus": "unaffected",
          "product": "kitty",
          "vendor": "kitty project",
          "versions": [
            {
              "lessThan": "0.41.0",
              "status": "affected",
              "version": "0",
              "versionType": "semver"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-346 Origin Validation Error"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}